name: GSI Build

on: [push]
    
env:
  ROM_URL: https://dl.google.com/developers/android/rvc/images/factory/walleye-rpb2.200611.009-factory-97f69fa0.zip
  ROM_NAME: Pixel
  TZ: America/Sao_Paulo
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/yukosky/ErfanGSIs -b runner

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Create env variable CAT_FILE
         run: echo "::set-env name=CAT_FILE::$(cat ErfanGSIs/output/*-Aonly-*.txt)"

       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt
